import turtle
def draw_square1 (t,sz):
    #este es el proceso de construccion del cuadrado original, el que tiene una cruz dentro de si
    t.begin_fill()
    t.forward(sz)
    t.right(90)
    t.forward(sz)
    t.right(90)
    t.forward(sz*2)
    t.right(90)
    t.forward(sz*2)
    t.right(90)
    t.forward(sz*2)
    t.right(90)
    t.forward(sz*2)
    t.right(90)
    t.forward(sz)
    t.right(90)
    t.forward(sz*2)
    t.left(90)
    t.forward(sz)
    t.left(90)
    t.forward(sz)
    t.left(90)
    t.forward(sz)
    t.left(15)
    t.end_fill()
wn = turtle.Screen()
wn.bgcolor("lightgreen")
tess = turtle.Turtle()
tess.color("blue","red")
tess.pensize(2)
tess.speed(1)
size = 100
for f in range (1):
    draw_square1 (tess,size)
wn.mainloop()
    